spring:
  application:
  name: cash-track

  datasource:
    url: jdbc:postgres:/localhost:5432/cashtrack
    name: postgres
    password: password
    driver-class-name: org.postgres.driver

  jpa:
    hibernate:
     ddl-auto: update
     show-sql: true

